services:
  mongodb:
    container_name: db-mongo
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=bases2_proyecto